In [3]:
import numpy as np

In [12]:
a = np.array([1.,2.,3.,4.,5.,6.])
a

array([1., 2., 3., 4., 5., 6.])

In [5]:
b = np.zeros((3,3))
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
c = np.ones((2,2))
c

array([[1., 1.],
       [1., 1.]])

In [8]:
d = np.arange(0,10,2)
d

array([0, 2, 4, 6, 8])

In [10]:
b.shape

(3, 3)

In [13]:
a.dtype

dtype('float64')

In [15]:
arr = np.arange(10)
arr[0]

np.int64(0)

In [16]:
arr[-1]

np.int64(9)

In [17]:
arr[2:5]

array([2, 3, 4])

In [18]:
arr[4:8:2]

array([4, 6])

In [19]:
matrix = np.arange(8).reshape(4,2)
matrix

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [21]:
matrix[2,1]

np.int64(5)

In [22]:
matrix[:,1]

array([1, 3, 5, 7])

In [23]:
matrix[0:1,0:1]

array([[0]])

In [26]:
arr1 = np.array([1,2,3])
arr2 = np.array([10,11,12])
arr1 + arr2

array([11, 13, 15])

In [27]:
arr1 * arr2

array([10, 22, 36])

In [28]:
arr2 / arr1

array([10. ,  5.5,  4. ])

In [29]:
arr1 * 5

array([ 5, 10, 15])

In [31]:
arr2.mean()

np.float64(11.0)

In [32]:
arr2.std()

np.float64(0.816496580927726)

In [33]:
x = np.array([10,20,25,30,41,49])
x_min = x.min()
x_max = x.max()

x_norm = (x - x_min) / (x_max - x_min)
x_norm

array([0.        , 0.25641026, 0.38461538, 0.51282051, 0.79487179,
       1.        ])